//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Replikit.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Replikit.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        internal static string UnavailableEventContext {
            get {
                return ResourceManager.GetString("UnavailableEventContext", resourceCulture);
            }
        }
        
        internal static string UserSessionNotAvailable {
            get {
                return ResourceManager.GetString("UserSessionNotAvailable", resourceCulture);
            }
        }
        
        internal static string ChannelSessionNotAvailable {
            get {
                return ResourceManager.GetString("ChannelSessionNotAvailable", resourceCulture);
            }
        }
        
        internal static string UserNotAvailable {
            get {
                return ResourceManager.GetString("UserNotAvailable", resourceCulture);
            }
        }
        
        internal static string NullSessionValue {
            get {
                return ResourceManager.GetString("NullSessionValue", resourceCulture);
            }
        }
        
        internal static string ControllerInvocationException {
            get {
                return ResourceManager.GetString("ControllerInvocationException", resourceCulture);
            }
        }
        
        internal static string ControllerPipelineException {
            get {
                return ResourceManager.GetString("ControllerPipelineException", resourceCulture);
            }
        }
        
        internal static string InvalidWrappedValueType {
            get {
                return ResourceManager.GetString("InvalidWrappedValueType", resourceCulture);
            }
        }
        
        internal static string AccountNotAvailable {
            get {
                return ResourceManager.GetString("AccountNotAvailable", resourceCulture);
            }
        }
        
        internal static string ChannelNotAvailable {
            get {
                return ResourceManager.GetString("ChannelNotAvailable", resourceCulture);
            }
        }
        
        internal static string MessageNotAvailable {
            get {
                return ResourceManager.GetString("MessageNotAvailable", resourceCulture);
            }
        }
        
        internal static string InvalidParameterContextType {
            get {
                return ResourceManager.GetString("InvalidParameterContextType", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedSetExtensionValue {
            get {
                return ResourceManager.GetString("UnauthenticatedSetExtensionValue", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedSetUsername {
            get {
                return ResourceManager.GetString("UnauthenticatedSetUsername", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedAddAccount {
            get {
                return ResourceManager.GetString("UnauthenticatedAddAccount", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedRemoveAccount {
            get {
                return ResourceManager.GetString("UnauthenticatedRemoveAccount", resourceCulture);
            }
        }
        
        internal static string CannotCreateUserInNonAccountEventContext {
            get {
                return ResourceManager.GetString("CannotCreateUserInNonAccountEventContext", resourceCulture);
            }
        }
        
        internal static string MiddlewareServiceNotAvailable {
            get {
                return ResourceManager.GetString("MiddlewareServiceNotAvailable", resourceCulture);
            }
        }
    }
}
